spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortnerdb
    username: root
    password: ronit@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#server:
#  servlet:
#    context-path: /urlshortner

jwt:
  secretKey: b383dd5118835215e962adef17c1c16b3d7631e57de4c2a9e108a86ffb5909d7
  expiration: 432000000

logging:
  level:
    org:
      springframework:
        security: DEBUG

      url_shortner: DEBUG

